spring:
    application:
        name: ModerationService

s3:
    endpoint-url: ${S3_ENDPOINT_URL}
    secret-key: ${S3_SECRET_KEY}
    access-key: ${S3_ACCESS_KEY}
    content-bucket-name: ${S3_BUCKET_CONTENTS_NAME:contents}

microservices:
    auth-service:
        url: ${AUTH_SERVICE_URL}
    article-service:
        url: ${ARTICLE_SERVICE_URL}